// <auto-generated />
using System;
using GerenciamentoCaixaPostal.Shared.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciamentoCaixaPostal.Shared.Data.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoCaixaPostal.Core.Shared.Models.CaixaPostal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataAluguel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdSocio")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatusCaixa")
                        .HasColumnType("integer");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSocio");

                    b.HasIndex("IdStatusCaixa");

                    b.ToTable("CaixasPostais", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Core.Shared.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.CaixaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CaixasStatus", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("IdClienteStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteStatus");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.ClienteStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientesStatus", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLiquidacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCaixaPostal")
                        .HasColumnType("integer");

                    b.Property<int>("IdCobrancaStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCaixaPostal");

                    b.HasIndex("IdCobrancaStatus");

                    b.ToTable("Cobrancas", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.CobrancaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CobrancasStatus", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormasPagamentos", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.HistoricoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCobranca")
                        .HasColumnType("integer");

                    b.Property<int>("IdFormaPagamento")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCobranca");

                    b.HasIndex("IdFormaPagamento");

                    b.ToTable("HistoricosPagamento", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Core.Shared.Models.CaixaPostal", b =>
                {
                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.Cliente", "Cliente")
                        .WithMany("CaixasPostais")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoCaixaPostal.Core.Shared.Models.Socio", "Socio")
                        .WithMany("CaixasPostais")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.CaixaStatus", "CaixaStatus")
                        .WithMany("CaixasPostais")
                        .HasForeignKey("IdStatusCaixa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaixaStatus");

                    b.Navigation("Cliente");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cliente", b =>
                {
                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.ClienteStatus", "ClienteStatus")
                        .WithMany("Clientes")
                        .HasForeignKey("IdClienteStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteStatus");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cobranca", b =>
                {
                    b.HasOne("GerenciamentoCaixaPostal.Core.Shared.Models.CaixaPostal", "CaixaPostal")
                        .WithMany("Cobrancas")
                        .HasForeignKey("IdCaixaPostal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.CobrancaStatus", "CobrancaStatus")
                        .WithMany("Cobrancas")
                        .HasForeignKey("IdCobrancaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaixaPostal");

                    b.Navigation("CobrancaStatus");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.HistoricoPagamento", b =>
                {
                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.Cobranca", "Cobranca")
                        .WithMany("historicoPagamentos")
                        .HasForeignKey("IdCobranca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoCaixaPostal.Shared.Core.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("historicoPagamentos")
                        .HasForeignKey("IdFormaPagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobranca");

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Core.Shared.Models.CaixaPostal", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Core.Shared.Models.Socio", b =>
                {
                    b.Navigation("CaixasPostais");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.CaixaStatus", b =>
                {
                    b.Navigation("CaixasPostais");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cliente", b =>
                {
                    b.Navigation("CaixasPostais");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.ClienteStatus", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.Cobranca", b =>
                {
                    b.Navigation("historicoPagamentos");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.CobrancaStatus", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("GerenciamentoCaixaPostal.Shared.Core.Models.FormaPagamento", b =>
                {
                    b.Navigation("historicoPagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
